name: publish

on:
  push:
    branches:
      - main

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          docker build . \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}:${BRANCH}-latest

      - name: Push Docker image
        run: |
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          docker push ghcr.io/${{ github.repository }}:${BRANCH}-latest
